// Package model contains the types for schema ''.
package model

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// AddressFrom represents a row from 'address_from'.
type AddressFrom struct {
	ID        int64 // id
	MailID    int64 // mail_id
	AddressID int64 // address_id

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the AddressFrom exists in the database.
func (af *AddressFrom) Exists() bool {
	return af._exists
}

// Deleted provides information if the AddressFrom has been deleted from the database.
func (af *AddressFrom) Deleted() bool {
	return af._deleted
}

// Insert inserts the AddressFrom to the database.
func (af *AddressFrom) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if af._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO address_from (` +
		`mail_id, address_id` +
		`) VALUES (` +
		`?, ?` +
		`)`

	// run query
	XOLog(sqlstr, af.MailID, af.AddressID)
	res, err := db.Exec(sqlstr, af.MailID, af.AddressID)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	af.ID = int64(id)
	af._exists = true

	return nil
}

// Update updates the AddressFrom in the database.
func (af *AddressFrom) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !af._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if af._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE address_from SET ` +
		`mail_id = ?, address_id = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, af.MailID, af.AddressID, af.ID)
	_, err = db.Exec(sqlstr, af.MailID, af.AddressID, af.ID)
	return err
}

// Save saves the AddressFrom to the database.
func (af *AddressFrom) Save(db XODB) error {
	if af.Exists() {
		return af.Update(db)
	}

	return af.Insert(db)
}

// Delete deletes the AddressFrom from the database.
func (af *AddressFrom) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !af._exists {
		return nil
	}

	// if deleted, bail
	if af._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM address_from WHERE id = ?`

	// run query
	XOLog(sqlstr, af.ID)
	_, err = db.Exec(sqlstr, af.ID)
	if err != nil {
		return err
	}

	// set deleted
	af._deleted = true

	return nil
}

// AddressByAddressID returns the Address associated with the AddressFrom's AddressID (address_id).
//
// Generated from foreign key 'address_from_address_id_fkey'.
func (af *AddressFrom) AddressByAddressID(db XODB) (*Address, error) {
	return AddressByID(db, af.AddressID)
}

// MailByMailID returns the Mail associated with the AddressFrom's MailID (mail_id).
//
// Generated from foreign key 'address_from_mail_id_fkey'.
func (af *AddressFrom) MailByMailID(db XODB) (*Mail, error) {
	return MailByID(db, af.MailID)
}

// AddressFromByID retrieves a row from 'address_from' as a AddressFrom.
//
// Generated from index 'address_from_id_pkey'.
func AddressFromByID(db XODB, id int64) (*AddressFrom, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, mail_id, address_id ` +
		`FROM address_from ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	af := AddressFrom{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&af.ID, &af.MailID, &af.AddressID)
	if err != nil {
		return nil, err
	}

	return &af, nil
}

// AddressFromsByAddressID retrieves a row from 'address_from' as a AddressFrom.
//
// Generated from index 'idx_address_from_address_id'.
func AddressFromsByAddressID(db XODB, addressID int64) ([]*AddressFrom, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, mail_id, address_id ` +
		`FROM address_from ` +
		`WHERE address_id = ?`

	// run query
	XOLog(sqlstr, addressID)
	q, err := db.Query(sqlstr, addressID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AddressFrom{}
	for q.Next() {
		af := AddressFrom{
			_exists: true,
		}

		// scan
		err = q.Scan(&af.ID, &af.MailID, &af.AddressID)
		if err != nil {
			return nil, err
		}

		res = append(res, &af)
	}

	return res, nil
}

// AddressFromsByMailID retrieves a row from 'address_from' as a AddressFrom.
//
// Generated from index 'idx_address_from_mail_id'.
func AddressFromsByMailID(db XODB, mailID int64) ([]*AddressFrom, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, mail_id, address_id ` +
		`FROM address_from ` +
		`WHERE mail_id = ?`

	// run query
	XOLog(sqlstr, mailID)
	q, err := db.Query(sqlstr, mailID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AddressFrom{}
	for q.Next() {
		af := AddressFrom{
			_exists: true,
		}

		// scan
		err = q.Scan(&af.ID, &af.MailID, &af.AddressID)
		if err != nil {
			return nil, err
		}

		res = append(res, &af)
	}

	return res, nil
}
