// Package model contains the types for schema ''.
package model

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// AddressCc represents a row from 'address_cc'.
type AddressCc struct {
	ID        int64 // id
	MailID    int64 // mail_id
	AddressID int64 // address_id

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the AddressCc exists in the database.
func (ac *AddressCc) Exists() bool {
	return ac._exists
}

// Deleted provides information if the AddressCc has been deleted from the database.
func (ac *AddressCc) Deleted() bool {
	return ac._deleted
}

// Insert inserts the AddressCc to the database.
func (ac *AddressCc) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if ac._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO address_cc (` +
		`mail_id, address_id` +
		`) VALUES (` +
		`?, ?` +
		`)`

	// run query
	XOLog(sqlstr, ac.MailID, ac.AddressID)
	res, err := db.Exec(sqlstr, ac.MailID, ac.AddressID)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	ac.ID = int64(id)
	ac._exists = true

	return nil
}

// Update updates the AddressCc in the database.
func (ac *AddressCc) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ac._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if ac._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE address_cc SET ` +
		`mail_id = ?, address_id = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, ac.MailID, ac.AddressID, ac.ID)
	_, err = db.Exec(sqlstr, ac.MailID, ac.AddressID, ac.ID)
	return err
}

// Save saves the AddressCc to the database.
func (ac *AddressCc) Save(db XODB) error {
	if ac.Exists() {
		return ac.Update(db)
	}

	return ac.Insert(db)
}

// Delete deletes the AddressCc from the database.
func (ac *AddressCc) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ac._exists {
		return nil
	}

	// if deleted, bail
	if ac._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM address_cc WHERE id = ?`

	// run query
	XOLog(sqlstr, ac.ID)
	_, err = db.Exec(sqlstr, ac.ID)
	if err != nil {
		return err
	}

	// set deleted
	ac._deleted = true

	return nil
}

// AddressByAddressID returns the Address associated with the AddressCc's AddressID (address_id).
//
// Generated from foreign key 'address_cc_address_id_fkey'.
func (ac *AddressCc) AddressByAddressID(db XODB) (*Address, error) {
	return AddressByID(db, ac.AddressID)
}

// MailByMailID returns the Mail associated with the AddressCc's MailID (mail_id).
//
// Generated from foreign key 'address_cc_mail_id_fkey'.
func (ac *AddressCc) MailByMailID(db XODB) (*Mail, error) {
	return MailByID(db, ac.MailID)
}

// AddressCcByID retrieves a row from 'address_cc' as a AddressCc.
//
// Generated from index 'address_cc_id_pkey'.
func AddressCcByID(db XODB, id int64) (*AddressCc, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, mail_id, address_id ` +
		`FROM address_cc ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	ac := AddressCc{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&ac.ID, &ac.MailID, &ac.AddressID)
	if err != nil {
		return nil, err
	}

	return &ac, nil
}

// AddressCcsByAddressID retrieves a row from 'address_cc' as a AddressCc.
//
// Generated from index 'idx_address_cc_address_id'.
func AddressCcsByAddressID(db XODB, addressID int64) ([]*AddressCc, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, mail_id, address_id ` +
		`FROM address_cc ` +
		`WHERE address_id = ?`

	// run query
	XOLog(sqlstr, addressID)
	q, err := db.Query(sqlstr, addressID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AddressCc{}
	for q.Next() {
		ac := AddressCc{
			_exists: true,
		}

		// scan
		err = q.Scan(&ac.ID, &ac.MailID, &ac.AddressID)
		if err != nil {
			return nil, err
		}

		res = append(res, &ac)
	}

	return res, nil
}

// AddressCcsByMailID retrieves a row from 'address_cc' as a AddressCc.
//
// Generated from index 'idx_address_cc_mail_id'.
func AddressCcsByMailID(db XODB, mailID int64) ([]*AddressCc, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, mail_id, address_id ` +
		`FROM address_cc ` +
		`WHERE mail_id = ?`

	// run query
	XOLog(sqlstr, mailID)
	q, err := db.Query(sqlstr, mailID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AddressCc{}
	for q.Next() {
		ac := AddressCc{
			_exists: true,
		}

		// scan
		err = q.Scan(&ac.ID, &ac.MailID, &ac.AddressID)
		if err != nil {
			return nil, err
		}

		res = append(res, &ac)
	}

	return res, nil
}
